### ISSUE TITLE
Changed the add Add dependant function to a quick button on grid screen please confirm the fields that need to read only  

### ISSUE THREAD

**Issue by DJRave** [charl26/transact#105]
@pdreyer

**Comment by pdreyer** [comment]
Not sure I understand where the ad will be now.
If you can please add a sscreenshot
Dependants can't update the Medical Aid information, it should display the parents and be readonly

**Comment by DJRave** [comment]
![Capture](https://user-images.githubusercontent.com/16910772/57344785-da908880-7148-11e9-9893-67a46a0b905f.PNG)
Clicking here on the + will take the user to the add Screen where the Medical aid info is populated from the user used and the save button changes to add dependant 
![Capture2](https://user-images.githubusercontent.com/16910772/57344890-3b1fc580-7149-11e9-8989-07f604c04ad6.PNG)
